exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'

EnableDefaultLinters: true  # ✅ ルートレベルに配置（linters: の外）

linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
